### ISSUE TITLE
orgmode

### ISSUE THREAD

**Issue by adelin-b** [amerlyq/nou.vim#3]
Hello, I found your project and it seems that you are rewriting orgmode, did you ever heard about it ?
Its used on emacs for a long time now and became pretty standard in organisation like .nou files, there is even phones and pwa application that can understand thoses files.

https://orgmode.org/
https://www.youtube.com/watch?v=7ybg3vjLQJM

**Comment by amerlyq** [comment]
@adelin-b, Thanks for the interest to the project!

I already mentioned org-mode in the main README file and don't quite get why you raised the issue?
Do you like org-mode very much and wish all developers had united and added even more features to it instead of spending their efforts on unnecessary one-person pet projects ? :)
Or do you miss full org-mode support from `vim-orgmode` project but don't want to learn emacs to get full feature set? :))

Sorry, but I don't like org-mode syntax, its conventional information architecture and its underlying concepts boundaries -- despite strongly appreciating the idea, which is quite similar to .nou.
It may be great for everybody (hereforth "standard in organisation"), but my own mental processes and physical habits work slightly differently and I value them enough to write my own diversity of plugins to accomodate them, instead of spending tons of efforts to change "standard" in the minds of others (which is praiseworthy but suicidal).

If somebody has similar exploration tendency, they may get some inspirations from my repo and even port some nice emergent features back to org-mode, and that's all really needed, isn't it?
